### ISSUE TITLE
Wrong mask in init_preprocessing for hcp7T

### ISSUE THREAD

**Issue by Paolopost** [brain-life/o3d-code#32]
The init_preprocessing doesn't work for hcp7t. The diagnostic message is not meaningful. Looking at the code it looks like there is a step of applying the mask to <file>.bvecs and <file>.bvals. These two kind of files should be simply copied. The mask should be applied only to the diffusion <file>.nii.gz.

**Comment by andnp** [comment]
Fixed with 5bd9de8
