### ISSUE TITLE
Redundant O3D_ prefix

### ISSUE THREAD

**Issue by Paolopost** [brain-life/o3d-code#33]
Currently there is a redundant prepending of the O3D_ prefix to the dataset (for example O3D_O3D_STN or O3D_O3D_HCP3T). There is a clash between the hypothesis that the dataset name is simply the lower case code, and the mapping of dataset_root dictionary. Probably the issue is located in the getAnatomy function in the copy_template.py module.

**Comment by andnp** [comment]
Oops, thanks for finding this!

Fixed with commit 90a315b
